# Generated by Django 2.2.5 on 2021-06-26 06:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_created', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='employeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_created', models.DateField(default=datetime.datetime.now)),
                ('employee_company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empman.companyModel')),
            ],
        ),
    ]
